# Generated by Django 4.0.4 on 2024-11-15 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of product (e.g. Сheesecake, Macaron, Cake.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Введіть короткий опис продукта', max_length=1000)),
                ('vaga', models.CharField(help_text='13 Character <a href="https://www.vaga-international.org/content/what-vaga">VAGA number</a>', max_length=13, verbose_name='VAGA')),
                ('filing', models.ManyToManyField(help_text='Виберіть начинку для цієї продукту', to='catalog.filing')),
            ],
        ),
        migrations.CreateModel(
            name='Vyrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('decor_name', models.CharField(max_length=100)),
                ('date_of_creation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Унікальний ідентифікатор цього конкретного виробу для всього каталога', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'В обговоренні'), ('o', 'В розгляді'), ('a', 'Доступний'), ('r', 'Зарезервований')], default='m', help_text='Наявність продукту', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vyrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vyrib'),
        ),
    ]
