# Generated by Django 4.0.4 on 2024-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='name',
            field=models.CharField(help_text='Enter the type of product (e.g. Шоколадна, Карамельна, Фруктова, Ягідна, Кокосова.)', max_length=200),
        ),
    ]
