# Generated by Django 4.0.4 on 2024-11-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_filing_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vyrib',
            options={'ordering': ['decor_name']},
        ),
    ]
