# Generated by Django 4.0.4 on 2024-11-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set product as returned'),)},
        ),
    ]
