# Generated by Django 4.0.4 on 2024-11-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='borrower',
            new_name='booked',
        ),
    ]
